apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-server
spec:
  selector:
    matchLabels:
      app: download-server
  replicas: 3
  template:
    metadata:
      labels:
        app: download-server
    spec:
      containers:
        - name: download-server
          image: ghcr.io/autodarts/download-server
          ports:
            - containerPort: 9090
              name: http
          imagePullPolicy: Always
      imagePullSecrets:
        - name: github-autodarts
---
apiVersion: v1
kind: Service
metadata:
  name: download-server
spec:
  selector:
    app: download-server
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: download-server
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: get.autodarts.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: download-server
                port:
                  name: http
  tls:
    - hosts:
        - get.autodarts.io
      secretName: autodarts-get-tls
